language: python

services:
  - mongodb

python:
  - "3.5"

script:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov freezegun
  - travis_retry pip install coveralls
  - cd dynamic
  - py.test --cov=.

#env:
#  - ENV=travis-ci

after_success:
  coveralls

notifications:
  email:
    on_success: never
    on_failure: always