language: python

services:
  - mongodb
  - redis-server

python:
  - "3.5"

script:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov freezegun
  - travis_retry pip install coveralls
  - cd dynamic
  - huey_consumer.py huey_tasks.huey -w 10 -l logs/huey.log
  - py.test --cov=.

after_success:
  coveralls

notifications:
  email:
    on_success: never
    on_failure: always