language: python

services:
  - redis-server

python:
  - "3.5"

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

script:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pytest-cov freezegun
  - travis_retry pip install coveralls
  - cd dynamic
  - py.test test --cov=.

after_success:
  coveralls

notifications:
  email:
    on_success: never
    on_failure: always